metricbeat.modules:
  - module: docker
    metricsets:
      - "container"
      - "cpu"
      - "diskio"
      - "event"
      - "healthcheck"
      - "info"
      - "memory"
      - "network"
    hosts: ["unix:///var/run/docker.sock"]
    period: 10s
    enabled: true

  - module: system
    period: 10s
    metricsets:
      - cpu
      - load
      - memory
      - network
      - process
      - process_summary
      - socket_summary
      #- core
      #- diskio
      #- socket
    process.include_top_n:
      by_cpu: 5      # include top 5 processes by CPU
      by_memory: 5   # include top 5 processes by memory

  - module: system
    period: 1m
    metricsets:
      - filesystem
      - fsstat
    processors:
    - drop_event.when.regexp:
        system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib)($|/)'
 
  - module: system
    period: 15m
    metricsets:
      - uptime

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

setup.dashboards.enabled: true
setup.template.enabled: true

setup.kibana:
  host: "kibana:5601"

output.elasticsearch:
  hosts: 'elasticsearch:9200'
  username: 'elastic'
  password: 'DzxTaAG2MDb1KjZneNFQ'